//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAccountingPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Income
    {
        [Required(ErrorMessage = "This field can not be empty.")]
        public long Id { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public long Amount { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string Description { get; set; }
        [Required(ErrorMessage = "This field can not be empty.")]
        public string Type { get; set; }
    }
}
